package Vista;

import Modelo.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;


public class NewJInternalProductos extends javax.swing.JInternalFrame {

    // Constructor que deshabilita el campo de ID de producto
    public NewJInternalProductos() {
        initComponents();      
        jTextid_producto.setEnabled(false); // El ID se genera automáticamente, así que se deshabilita
    }
    
    
    // Método para limpiar los campos de texto
    public void LimpiarCampos(){
        jTextid_producto.setText("");
        jTextnombre.setText("");
        jTextdescripcion.setText("");
        jTextprecio.setText("");
    }
    
    
    // Método para obtener y mostrar todos los productos en la tabla
   public void obtenerDatos(){       
    try {
        
        // Se obtiene una lista de productos de la base de datos
        List <Productos> productos = new DAOProductos().ObtenerDatos();
        DefaultTableModel modelo = new DefaultTableModel();
        
        // Se definen las columnas de la tabla
        String[] columnas = {"id_producto", "nombre", "descripcion", "precio"};
        modelo.setColumnIdentifiers(columnas);
        
        // Se llena la tabla con los datos de cada producto
        for(Productos pro : productos){
            String[] renglon = {
                Integer.toString(pro.getId_producto()),
                pro.getNombre(),
                pro.getDescripcion(),
                pro.getPrecio().toString()
            };
            modelo.addRow(renglon);
        }
        jTableproducto.setModel(modelo); // Se actualiza la tabla en la interfaz
      }catch(Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(rootPane, "Error al obtener los datos de productos.");
    }
    
}

   // Método para actualizar la información de un producto
    public void actualizarProducto() {
    int id=Integer.parseInt(this.jTextid_producto.getText());
     String nomb=this.jTextnombre.getText();       
     String desc=this.jTextdescripcion.getText();        
     float prec=Float.parseFloat(this.jTextprecio.getText());
     
     // Actualiza el producto en la base de datos
     DAOProductos dao=new DAOProductos();
     int res=dao.Actualizar (id, nomb, desc, prec);
     
     // Muestra un mensaje según el resultado de la actualización
     if (res ==1) {
         JOptionPane.showMessageDialog(rootPane, "Producto Actualizado!");
     }else{
         JOptionPane.showMessageDialog(rootPane, "¡Ocurrió un ERROR!");
     }  
     
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextid_producto = new javax.swing.JTextField();
        jTextnombre = new javax.swing.JTextField();
        jTextdescripcion = new javax.swing.JTextField();
        jTextprecio = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButtonAgregar = new javax.swing.JButton();
        jButtonActualizar = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableproducto = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 264, Short.MAX_VALUE)
        );

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registar Producto", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 78, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("ID_Producto");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 31, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Descripcion");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 90, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Precio");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 55, -1));
        jPanel1.add(jTextid_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 31, 164, 17));

        jTextnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextnombreActionPerformed(evt);
            }
        });
        jPanel1.add(jTextnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 82, 174, -1));

        jTextdescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextdescripcionActionPerformed(evt);
            }
        });
        jPanel1.add(jTextdescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 174, -1));

        jTextprecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextprecioActionPerformed(evt);
            }
        });
        jPanel1.add(jTextprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 124, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 560, 170));

        jButtonAgregar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonAgregar.setText("Agregar ");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });

        jButtonActualizar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonActualizar.setText("Actualizar");
        jButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarActionPerformed(evt);
            }
        });

        jButtonBorrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonBorrar.setText("Borrar");
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });

        jButtonEditar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jButtonAgregar)
                .addGap(106, 106, 106)
                .addComponent(jButtonActualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(jButtonBorrar)
                .addGap(72, 72, 72))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jButtonBuscar)
                .addGap(87, 87, 87)
                .addComponent(jButtonEditar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAgregar)
                    .addComponent(jButtonActualizar)
                    .addComponent(jButtonBorrar))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBuscar)
                    .addComponent(jButtonEditar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 560, 90));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Productos registrados", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jTableproducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableproducto);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 540, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents
// Método llamado al hacer clic en "Agregar" para insertar un nuevo producto
    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        String nomb=jTextnombre.getText();
        String desc=jTextdescripcion.getText();
        float prec=Float.parseFloat(this.jTextprecio.getText());
        
        // Valida que los campos no estén vacíos
        if (nomb.contentEquals("")|| desc.contentEquals("")|| prec==0){
             JOptionPane.showMessageDialog(rootPane,
                "Todos los campos son obligatorios");
        }else{
            try{
                Productos pro=new DAOProductos().Insertar(nomb, desc, prec);
                 JOptionPane.showMessageDialog(rootPane, "Registro agregado");
            }catch(Exception e){
                 e.printStackTrace();
                JOptionPane.showMessageDialog(rootPane, "No se agregó el registro");
            }
        }
        obtenerDatos();// Actualiza la tabla
        LimpiarCampos(); // Limpia los campos de texto
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    // Método para llenar los campos con los datos del producto seleccionado en la tabla para editarlo
    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
         int fila=this.jTableproducto.getSelectedRow();//Se obtiene la fila seleccionada
            if (fila==-1) {
                JOptionPane.showMessageDialog(rootPane, "Seleccione un registro de la tabla");
            }
                        else{ //Se toma cada campo de la tabla del registro seleccionado
                // y se asgina a una variable
                try{
                    // Captura los datos del producto seleccionado
                    int id=Integer.parseInt((String) this.jTableproducto.getValueAt (fila, 0).toString());
                    String nomb=(String) this.jTableproducto.getValueAt (fila,1);
                    String desc=(String) this.jTableproducto.getValueAt (fila, 2);
                    String prec=(String) this.jTableproducto.getValueAt (fila,3);
                    
                    // Muestra los datos en los campos de texto para su edición
                    jTextid_producto.setText(""+id);
                    jTextnombre.setText(nomb);
                    jTextdescripcion.setText (desc);
                    jTextprecio.setText(prec);

                 
                } catch (NumberFormatException e) {
                    e.printStackTrace();
                }
            }
    }//GEN-LAST:event_jButtonEditarActionPerformed

    // Método llamado al hacer clic en "Actualizar" para guardar los cambios en el producto
    private void jButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarActionPerformed
        actualizarProducto();
        obtenerDatos();
        LimpiarCampos();
    }//GEN-LAST:event_jButtonActualizarActionPerformed

    // Método llamado al hacer clic en "Borrar" para eliminar el producto seleccionado
    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        int fila=this.jTableproducto.getSelectedRow();   
      if (fila==-1){
      JOptionPane.showMessageDialog(rootPane, "Seleccione un registro de la tabla");    
    }else {
     int id=Integer.parseInt((String) this.jTableproducto.getValueAt (fila, 0).toString());
     DAOProductos dao=new DAOProductos();
     dao.Eliminar (id);
     obtenerDatos ();
         }
    }//GEN-LAST:event_jButtonBorrarActionPerformed

    private void jTextnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextnombreActionPerformed

    private void jTextprecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextprecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextprecioActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jTextdescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextdescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextdescripcionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActualizar;
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableproducto;
    private javax.swing.JTextField jTextdescripcion;
    private javax.swing.JTextField jTextid_producto;
    private javax.swing.JTextField jTextnombre;
    private javax.swing.JTextField jTextprecio;
    // End of variables declaration//GEN-END:variables
}
